global:
    scrape_interval: 15s

scrape_configs:
    - job_name: "ispindel"
      scrape_interval: 90s
      honor_labels: true
      metrics_path: /metrics
      static_configs:
          - targets: ["pushgateway:9091"]
        labels:
            service: 'pushgateway'